force-app/main/default/objects/Interviewer__c/Interviewer__c.object-meta.xml
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <label>Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InterviewerAssignmentService.cls
global with sharing class InterviewerAssignmentService {
    @AuraEnabled(cacheable=true)
    public static List<Panel__c> getPanelList(){
        try {
            return [SELECT Id, Name FROM Panel__c];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void assignInterviewerToPanel(String userEmail, Id panelId){
        try {
            List<User> user = [SELECT Id, Name, Email FROM User WHERE Email =:userEmail LIMIT 1];
            Interviewer__c interviewer = new Interviewer__c(User__c=user[0].Id, Panel__c=panelId);
            insert interviewer;
        } catch (Exception e) {
            throw new AuraHandledException('Assignment of Interviewer failed! User not found in the org database.');
        }
    }
}