force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/HiringEventId__c.field-meta.xml
<CustomField>
    <fullName>HiringEventId__c</fullName>
    <label>Hiring Event</label>
    <referenceTo>Hiring_Event__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hiring_Event__c/Hiring_Event__c.object-meta.xml
<CustomObject>
    <label>Hiring Event</label>
    <nameField>
        <label>Hiring Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Event__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Hiring Events</relationshipLabel>
    <relationshipName>Hiring_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/HiringEventItem__c.object-meta.xml
<CustomObject>
    <label>Hiring Event Item</label>
    <nameField>
        <label>HiringEventItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HiringEventItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HiringEventItem__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>HiringEventItems</relationshipLabel>
    <relationshipName>HiringEventItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/CandidateId__c.field-meta.xml
<CustomField>
    <fullName>CandidateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>HiringEventItems</relationshipLabel>
    <relationshipName>HiringEventItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/HiringEvent__c.field-meta.xml
<CustomField>
    <fullName>HiringEvent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring Event</label>
    <referenceTo>Hiring_Event__c</referenceTo>
    <relationshipLabel>HiringEventItems</relationshipLabel>
    <relationshipName>HiringEventItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/HiringEventId__c.field-meta.xml
<CustomField>
    <fullName>HiringEventId__c</fullName>
    <formula>CandidateId__r.HiringEventId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hiring Event Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R1Round__c.field-meta.xml
<CustomField>
    <fullName>R1Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>R1 Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>HiringEventItems</relationshipLabel>
    <relationshipName>HiringEventItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R2Round__c.field-meta.xml
<CustomField>
    <fullName>R2Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>R2 Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>HiringEventItems (Round 2)</relationshipLabel>
    <relationshipName>HiringEventItems1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R3Round__c.field-meta.xml
<CustomField>
    <fullName>R3Round__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>R3 Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>HiringEventItems (R3 Round)</relationshipLabel>
    <relationshipName>HiringEventItems2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/Interviewer__c.object-meta.xml
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <label>Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <label>Round</label>
    <nameField>
        <label>Round Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Round__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Rounds</relationshipLabel>
    <relationshipName>Rounds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round__c/fields/HiringEvent__c.field-meta.xml
<CustomField>
    <fullName>HiringEvent__c</fullName>
    <label>Hiring Event</label>
    <referenceTo>Hiring_Event__c</referenceTo>
    <relationshipLabel>Rounds</relationshipLabel>
    <relationshipName>Rounds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Round__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>Interviewer__c</referenceTo>
    <relationshipLabel>Rounds</relationshipLabel>
    <relationshipName>Rounds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round__c/fields/RoundStatus__c.field-meta.xml
<CustomField>
    <fullName>RoundStatus__c</fullName>
    <label>Round Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Round__c/fields/SiftLink__c.field-meta.xml
<CustomField>
    <fullName>SiftLink__c</fullName>
    <label>SIFT Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/InterviewerAssignmentServiceTest.cls
@isTest
public class InterviewerAssignmentServiceTest {
    public InterviewerAssignmentServiceTest() {

    }

    @TestSetup
    static void makeData(){
        Panel__c panel = new Panel__c(Name = 'New Panel');
        insert panel;
        Hiring_Event__c he = new Hiring_Event__c(Panel__c = panel.Id,   Date__c =  Date.today());
        insert he;
        Candidate__c can = new Candidate__c(HiringEventId__c=he.Id, Name = 'Satish',Email__c='satish@gmail.com');
        insert can;
        Interviewer__c inter = new Interviewer__c(Panel__c=panel.Id, User__c=UserInfo.getUserId());
        insert inter;
        Round__c round1 = new Round__c(  Candidate__c=can.Id, HiringEvent__c=he.Id,  Interviewer__c = inter.Id, Name = 'Round1', StartTime__c=DateTime.now(), 
                                            RoundStatus__c='In Progress', SiftLink__c='https://www.salesforce.com');
        insert round1;
        Round__c round2 = new Round__c(  Candidate__c=can.Id, HiringEvent__c=he.Id,  Interviewer__c = inter.Id, Name = 'Round2', StartTime__c=DateTime.now());
        insert round2;
        Round__c round3 = new Round__c(  Candidate__c=can.Id, HiringEvent__c=he.Id,  Interviewer__c = inter.Id, Name = 'Round3', StartTime__c=DateTime.now());
        insert round3;
        HiringEventItem__c item = new HiringEventItem__c(HiringEvent__c=he.id, CandidateId__c=can.id, R1Round__c=round1.id, R2Round__c=round2.id, R3Round__c=round3.id);
        insert item;

    }

    @isTest
    static void getPanelListTest()
    {
        try{
            List<Panel__c> panelList = InterviewerAssignmentService.getPanelList();
        }catch(Exception ex){}
    }

    @isTest
    static void assignInterviewerToPanelTest()
    {
        try{
            String userEmail = [SELECT Id,Email FROM User WHERE Id = :UserInfo.getUserId()][0].Email;
            Id panelId = [SELECT Id FROM Panel__c][0].Id;
            InterviewerAssignmentService.assignInterviewerToPanel(userEmail,panelId);
        }catch(Exception ex){}
    }

    
}