force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/HiringEventId__c.field-meta.xml
<CustomField>
    <fullName>HiringEventId__c</fullName>
    <label>Hiring Event</label>
    <referenceTo>Hiring_Event__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/ResumeLink__c.field-meta.xml
<CustomField>
    <fullName>ResumeLink__c</fullName>
    <label>Resume Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMTS</fullName>
            </value>
            <value>
                <fullName>MTS</fullName>
            </value>
            <value>
                <fullName>SMTS</fullName>
            </value>
            <value>
                <fullName>LMTS</fullName>
            </value>
            <value>
                <fullName>Software Engineering AMTS</fullName>
                <isActive>false</isActive>
                <label>Software Engineering AMTS</label>
            </value>
            <value>
                <fullName>Software Engineering LMTS</fullName>
                <isActive>false</isActive>
                <label>Software Engineering LMTS</label>
            </value>
            <value>
                <fullName>Software Engineering MTS</fullName>
                <isActive>false</isActive>
                <label>Software Engineering MTS</label>
            </value>
            <value>
                <fullName>Software Engineering SMTS</fullName>
                <isActive>false</isActive>
                <label>Software Engineering SMTS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loop Cut</fullName>
            </value>
            <value>
                <fullName>Internet Issue</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Time Break</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hiring_Event__c/Hiring_Event__c.object-meta.xml
<CustomObject>
    <label>Hiring Event</label>
    <nameField>
        <label>Hiring Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HiringEventItem__c/HiringEventItem__c.object-meta.xml
<CustomObject>
    <label>Hiring Event Item</label>
    <nameField>
        <label>HiringEventItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HiringEventItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HiringEventItem__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>HiringEventItems</relationshipLabel>
    <relationshipName>HiringEventItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/CodepairLink__c.field-meta.xml
<CustomField>
    <fullName>CodepairLink__c</fullName>
    <label>Codepair Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/HiringEvent__c.field-meta.xml
<CustomField>
    <fullName>HiringEvent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring Event</label>
    <referenceTo>Hiring_Event__c</referenceTo>
    <relationshipLabel>HiringEventItems</relationshipLabel>
    <relationshipName>HiringEventItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/HiringEventId__c.field-meta.xml
<CustomField>
    <fullName>HiringEventId__c</fullName>
    <formula>CandidateId__r.HiringEventId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hiring Event Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/InterviewLink__c.field-meta.xml
<CustomField>
    <fullName>InterviewLink__c</fullName>
    <label>Interview Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R1Feedback__c.field-meta.xml
<CustomField>
    <fullName>R1Feedback__c</fullName>
    <formula>R1Round__r.Feedback__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>R1 Feedback</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R1Interviewer__c.field-meta.xml
<CustomField>
    <fullName>R1Interviewer__c</fullName>
    <formula>R1Round__r.Interviewer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>R1 Interviewer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R1Observer__c.field-meta.xml
<CustomField>
    <fullName>R1Observer__c</fullName>
    <formula>R1Round__r.Observer__c</formula>
    <label>R1 Observer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R1RoundStatus__c.field-meta.xml
<CustomField>
    <fullName>R1RoundStatus__c</fullName>
    <formula>TEXT( R1Round__r.RoundStatus__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>R1 Round Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R1SiftLink__c.field-meta.xml
<CustomField>
    <fullName>R1SiftLink__c</fullName>
    <formula>R1Round__r.SiftLink__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>R1 SIFT Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R1StartTime__c.field-meta.xml
<CustomField>
    <fullName>R1StartTime__c</fullName>
    <label>R1 Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R2Feedback__c.field-meta.xml
<CustomField>
    <fullName>R2Feedback__c</fullName>
    <label>R2 Feedback</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R2Interviewer__c.field-meta.xml
<CustomField>
    <fullName>R2Interviewer__c</fullName>
    <formula>R2Round__r.Interviewer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>R2 Interviewer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R2Observer__c.field-meta.xml
<CustomField>
    <fullName>R2Observer__c</fullName>
    <label>R2 Observer</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R2RoundStatus__c.field-meta.xml
<CustomField>
    <fullName>R2RoundStatus__c</fullName>
    <label>R2 Round Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R2SiftLink__c.field-meta.xml
<CustomField>
    <fullName>R2SiftLink__c</fullName>
    <label>R2 SIFT Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R2StartTime__c.field-meta.xml
<CustomField>
    <fullName>R2StartTime__c</fullName>
    <formula>DATETIMEVALUE( R2Round__r.StartTime__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>R2 Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R3Feedback__c.field-meta.xml
<CustomField>
    <fullName>R3Feedback__c</fullName>
    <formula>R3Round__r.Feedback__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>R3 Feedback</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R3Interviewer__c.field-meta.xml
<CustomField>
    <fullName>R3Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>R3 Interviewer</label>
    <referenceTo>Interviewer__c</referenceTo>
    <relationshipLabel>HiringEventItems (R3 Interviewer)</relationshipLabel>
    <relationshipName>HiringEventItems2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R3Observer__c.field-meta.xml
<CustomField>
    <fullName>R3Observer__c</fullName>
    <label>R3 Observer</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R3RoundStatus__c.field-meta.xml
<CustomField>
    <fullName>R3RoundStatus__c</fullName>
    <label>R3 Round Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R3SiftLink__c.field-meta.xml
<CustomField>
    <fullName>R3SiftLink__c</fullName>
    <label>R3 SIFT Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/R3StartTime__c.field-meta.xml
<CustomField>
    <fullName>R3StartTime__c</fullName>
    <formula>DATETIMEVALUE( R3Round__r.StartTime__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>R3 Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/ResumeLink__c.field-meta.xml
<CustomField>
    <fullName>ResumeLink__c</fullName>
    <formula>CandidateId__r.ResumeLink__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resume Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HiringEventItem__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role Evaluation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventItemsController.cls
global with sharing class EventItemsController {
  @AuraEnabled(cacheable=true)
  public static List<HiringEventItem__c> getAllEventItem(String eventId) {
      List<HiringEventItem__c> eventItemList = [
        SELECT 
          Id,
          Candidate__r.Id,
          Candidate__r.Name,
          Candidate__r.CodepairLink__c,
          Candidate__r.Contact__c,
          Candidate__r.Email__c,
          Candidate__r.HiringEventId__c,
          Candidate__r.InterviewLink__c,
          Candidate__r.ResumeLink__c,
          Candidate__r.Role__c,
          Candidate__r.Status__c,
          Round1__r.Id,
          R1RoundStatus__c,
          R1Interviewer__c,
          R1StartTime__c,
          R1Feedback__c,
          R1SiftLink__c,
          R1Observer__c,
          Round2__r.Id,
          R2RoundStatus__c,
          R2Interviewer__c,
          R2StartTime__c,
          R2Feedback__c,
          R2SiftLink__c,
          R2Observer__c,
          Round3__r.Id,
          R3RoundStatus__c,
          R3Interviewer__c,
          R3StartTime__c,
          R3Feedback__c,
          R3SiftLink__c,
          R3Observer__c
          FROM HiringEventItem__c WHERE  HiringEvent__r.Id=:eventId];
          System.debug('itemList:: '+eventItemList);
      return eventItemList;
  }

  @AuraEnabled(cacheable=true)
  public static List<HiringEventItem__c> getEventItem(String eventItemId) {
      List<HiringEventItem__c> eventItemList = [
        SELECT 
        Id,
          Candidate__r.Id,
          Candidate__r.Name,
          Candidate__r.CodepairLink__c,
          Candidate__r.Contact__c,
          Candidate__r.Email__c,
          Candidate__r.HiringEventId__c,
          Candidate__r.InterviewLink__c,
          Candidate__r.ResumeLink__c,
          Candidate__r.Role__c,
          Candidate__r.Status__c,
          Round1__r.Id,
          R1RoundStatus__c,
          R1Interviewer__c,
          R1StartTime__c,
          R1Feedback__c,
          R1SiftLink__c,
          R1Observer__c,
          Round2__r.Id,
          R2RoundStatus__c,
          R2Interviewer__c,
          R2StartTime__c,
          R2Feedback__c,
          R2SiftLink__c,
          R2Observer__c,
          Round3__r.Id,
          R3RoundStatus__c,
          R3Interviewer__c,
          R3StartTime__c,
          R3Feedback__c,
          R3SiftLink__c,
          R3Observer__c
          FROM HiringEventItem__c WHERE  Id=:eventItemId];
          System.debug('itemList:: '+eventItemList);
      return eventItemList;
  }

  @AuraEnabled
  public static void setEventItem(
    Id selectedEventId,
    String candidateStatus,
    String R1Interviewer,
    String R1Observer,
    DateTime R1Time,
    String R1Sift,
    String R1Feedback) 
    {
      List<HiringEventItem__c> items = [ SELECT
        Id,
          Candidate__r.Id,
          Candidate__r.Status__c,
          Round1__r.Id,
          R1RoundStatus__c,
          R1Interviewer__c,
          R1StartTime__c,
          R1Feedback__c,
          R1SiftLink__c,
          R1Observer__c,
          Round2__c,
          R2RoundStatus__c,
          R2Interviewer__c,
          R2StartTime__c,
          R2Feedback__c,
          R2SiftLink__c,
          R2Observer__c,
          Round3__c,
          R3RoundStatus__c,
          R3Interviewer__c,
          R3StartTime__c,
          R3Feedback__c,
          R3SiftLink__c,
          R3Observer__c
          FROM HiringEventItem__c WHERE  Id=:selectedEventId LIMIT 1];
      
      List<Candidate__c> candidateList = [Select Id, Status__c from Candidate__c where Id = :items[0].Candidate__r.Id];
      if(candidateStatus != null) 
      {
        candidateList[0].Status__c = candidateStatus;
        update candidateList;
      }
      if(R1Interviewer != null) 
      {
        items[0].R1Interviewer__c = R1Interviewer;

      }
      if(R1Observer != null) items[0].R1Observer__c = R1Observer;
      if(R1Sift != null) items[0].R1SiftLink__c = R1Sift;
      if(R1Time != null) items[0].R1StartTime__c = R1Time;
      if(R1Feedback != null) items[0].R1Feedback__c = R1Feedback;
System.debug('Prit: before update:'+ items);
      update items;
    }

}