force-app/main/default/objects/Hiring_Event__c/Hiring_Event__c.object-meta.xml
<CustomObject>
    <label>Hiring Event</label>
    <nameField>
        <label>Hiring Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Event__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Hiring Events</relationshipLabel>
    <relationshipName>Hiring_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <label>Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EventsControllerTest.cls
@isTest
public class EventsControllerTest {
    public EventsControllerTest() {

    }
    @TestSetup
    static void makeData(){
        Panel__c panel = new Panel__c(Name = 'New Panel');
        insert panel;
        Hiring_Event__c he = new Hiring_Event__c(Panel__c = panel.Id,   Date__c =  Date.today());
        insert he;
        he = new Hiring_Event__c(Panel__c = panel.Id,   Date__c =  Date.today().addDays(-2));
        insert he;
    }

    @isTest
    static void getFutureEventsTest()
    {
        try{
            EventsController.getFutureEvents();
        }
        catch(Exception ex){}
    }

    @isTest
    static void getPastEventsTest()
    {
        try{
            EventsController.getPastEvents();
        }catch(Exception ex){}
    }

}