force-app/main/default/objects/Hiring_Event__c/Hiring_Event__c.object-meta.xml
<CustomObject>
    <label>Hiring Event</label>
    <nameField>
        <label>Hiring Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Event__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Hiring Events</relationshipLabel>
    <relationshipName>Hiring_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <label>Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EventsController.cls
public inherited sharing class EventsController {
    @AuraEnabled(cacheable=true)
    public static List<Hiring_Event__c> getFutureEvents() {
        Date today = Date.today();
        List<Hiring_Event__c> events= [select CreatedDate, Date__c, Panel__r.Name, Id, Name, Owner.Name from Hiring_Event__c where Date__c >= today];
        return events;

    }

    @AuraEnabled(cacheable=true)
    public static List<Hiring_Event__c> getPastEvents() {
        Date today = Date.today();
        List<Hiring_Event__c> events= [select CreatedDate, Date__c, Panel__r.Name, Id, Name, Owner.Name from Hiring_Event__c where Date__c < today];
        return events;

    }
}